src/Entity/Adress.php
<?php

/*
 * Imageur_Symfony
 * Symfony 5
 * Christine Zedday
 */

namespace App\Entity;

use App\Repository\AdressRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=adressRepository::class)
 */
class Adress
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $physique;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $url;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $relative_accueil;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $relative_fichiers;

    /**
     * @ORM\ManyToOne(targetEntity=Site::class, inversedBy="adresses")
     */
    private $site;

    public function getId(): ?int
    {
        return $this->id;
    }


    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPhysique(): ?string
    {
        return $this->physique;
    }

    public function setPhysique(string $physique): self
    {
        $this->physique = $physique;

        return $this;
    }

    public function getUrl(): ?string
    {
        return $this->url;
    }

    public function setUrl(string $url): self
    {
        $this->url = $url;

        return $this;
    }

    public function getRelativeAccueil(): ?string
    {
        return $this->relative_accueil;
    }

    public function setRelativeAccueil(string $relative_accueil): self
    {
        $this->relative_accueil = $relative_accueil;

        return $this;
    }

    public function getRelativeFichiers(): ?string
    {
        return $this->relative_fichiers;
    }

    public function setRelativeFichiers(string $relative_fichiers): self
    {
        $this->relative_fichiers = $relative_fichiers;

        return $this;
    }

    public function getSite(): ?site
    {
        return $this->site;
    }

    public function setSite(?Site $site): self
    {
        $this->site = $site;

        return $this;
    }
}

src/Form/AdressType.php
<?php

/*
 * Imageur_Symfony
 * Symfony 5
 * Christine Zedday
 */

namespace App\Form;

use App\Entity\Adress;
use App\Entity\Site;
use Symfony\Component\Form\AbstractType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AdressType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nom')
            ->add('physique')
            ->add('url')
            ->add('relative_accueil')
            ->add('relative_fichiers')
            ->add('site', EntityType::class, [
                'class' => Site::class,
                'choice_label' => 'nom',
                'multiple' => false,
                'mapped' => true,
                'required' => true, ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Adress::class,
        ]);
    }
}

src/Controller/AdressController.php
<?php

/*
 * Imageur_Symfony
 * Symfony 5
 * Christine Zedday
 */

namespace App\Controller;

use App\Entity\Adress;
use App\Form\AdressType;
use App\Repository\AdressRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/adress")
 */
class AdressController extends AbstractController
{
    /**
     * @Route("/", name="adress_index", methods={"GET"})
     */
    public function index(AdressRepository $adressRepository): Response
    {
        return $this->render('adress/index.html.twig', [
            'adresses' => $adressRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="adress_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $adress = new Adress();
        $form = $this->createForm(adressType::class, $adress);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($adress);
            $entityManager->flush();

            return $this->redirectToRoute('adress_index');
        }

        return $this->render('adress/new.html.twig', [
            'adress' => $adress,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="adress_show", methods={"GET"})
     */
    public function show(Adress $adress): Response
    {
        return $this->render('adress/show.html.twig', [
            'adress' => $adress,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="adress_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, adress $adress): Response
    {
        $form = $this->createForm(AdressType::class, $adress);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('adress_show',  array('id' => $adress->getId()));

            
        }

        return $this->render('adress/edit.html.twig', [
            'adress' => $adress,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="adress_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Adress $adress): Response
    {
        if ($this->isCsrfTokenValid('delete'.$adress->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($adress);
            $entityManager->flush();
        }

        return $this->redirectToRoute('adress_index');
       
    }
}

templates/adress/_delete_form.html.twig
<form method="post" action="{{ path('adress_delete', {'id': adress.id}) }}" onsubmit="return confirm('C'est peut-être pas une bonne idée, les adresses sont utilisées par le générateur de fichiers!');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ adress.id) }}">
    <button class="btn">Delete</button>
</form>

templates/adress/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Enregistrer') }}</button>
{{ form_end(form) }}

templates/adress/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit address{% endblock %}

{% block content %}
    <h1>Modifier une adresse</h1>

 <p>   {{ include('adress/_form.html.twig', {'button_label': 'Mettre à jour'}) }} </p>

  <p>  <a href="{{ path('adress_index') }}">Retour à la liste</a></p>
  <p>  <a href="{{ path('adress_show', {id: adress.id}) }}">Voir</a></p>
  <p>Ne pas modifier les noms des adresses, ils sont utilisés par le programme! Modifier les adresses pour qu'elle pointent vers les éléments de votre site.</p>


   
{% endblock %}

templates/adress/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}adress index{% endblock %}

{% block content %}
    <h1>Index des adresses</h1>
    <p>   <a href="{{ path('adress_new') }}">Ajouter une adresse</a> (si vous voulez que le programme la prenne en compte, il faudra vous en occuper)</p>
    <p>Adresse physique: emplacement du disque dur ou devra être généré tel type de fichier an attendant de le mettre en ligne.<br/>
     <p>URL: le lien qui permet de visionner le fichier généré.<br/>
       <p>Relative accueil: pour générer les liens de navigation de la page d'accueil (index.php qui se trouve en principe à la racine du site). Cette adresse est relative pour rester valable sur le site en ligne.<br/>
         <p>Relative fichiers: pour générer les liens de navigation des articles.<br/>
    </p>

    <table class="table">
        <thead>
            <tr>
               <th>Site</th>
                <th>Nom</th>
                <th>Physique</th>
                <th>Url</th>
                <th>Relative_accueil</th>
                <th>Relative_fichiers</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for adress in adresses %}
            <tr>
                <td>{% if adress.site|default %}
{{adress.site.nom}}
{% endif %}</td>
                <td>{{ adress.nom }}</td>
                <td>{{ adress.physique }}</td>
                <td>{{ adress.url }}</td>
                <td>{{ adress.relativeAccueil }}</td>
                <td>{{ adress.relativeFichiers }}</td>
                <td>
                    <a href="{{ path('adress_show', {'id': adress.id}) }}"> {{ include('./_showicone.html.twig')}}</a>
                    <a href="{{ path('adress_edit', {'id': adress.id}) }}"> {{ include('./_editicone.html.twig')}}</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">Pas d'adresses enregistrées</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

 
   {{ include('./_crediticones.html.twig')}}
   
{% endblock %}

templates/adress/new.html.twig
{% extends 'base.html.twig' %}


{% block title %}Nouvelle adresse{% endblock %}


{% block content %}
    <h1>Créer une nouvelle adresse</h1>

    {{ include('adress/_form.html.twig') }}

    <p><a href="{{ path('adress_index') }}">Retour à la liste</a></p>
    
{% endblock %}

templates/adress/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}adresse{% endblock %}

{% block content %}
    <h1>adresse</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ adress.id }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ adress.nom }}</td>
            </tr>
            <tr>
                <th>Physique</th>
                <td>{{ adress.physique }}</td>
            </tr>
            <tr>
                <th>Url</th>
                <td>{{ adress.url }}</td>
            </tr>
            <tr>
                <th>Relative_accueil</th>
                <td>{{ adress.relativeAccueil }}</td>
            </tr>
            <tr>
                <th>Relative_fichiers</th>
                <td>{{ adress.relativeFichiers }}</td>
            </tr>
        </tbody>
    </table>

 <p>   <a href="{{ path('adress_index') }}">Retour à la liste</a></p>

 <p>   <a href="{{ path('adress_edit', {'id': adress.id}) }}">Modifier</a></p>

   
  
{% endblock %}